---
version: 0.2
phases:
  pre_build:
    commands:
      - export DOCKER_IMAGE_NAME="${ECR_REPOSITORY}:hyperbol_api-$(date +"%s")"
      - mkdir -p build_artifacts

  build:
    commands:
      - docker build --pull --tag="${DOCKER_IMAGE_NAME}" .

  post_build:
    commands:
      - >-
        aws ecr get-login-password --region "$(echo ${ECR_REPOSITORY} | cut -d '.' -f 4)"
        | docker login --username AWS --password-stdin "$(echo ${ECR_REPOSITORY} | cut -d '/' -f 1)"
      - docker push "${DOCKER_IMAGE_NAME}"
      - cp template.yml build_artifacts/${DEPLOY_TEMPLATE_FILE_NAME}
      - >-
        echo "{\"Parameters\": {\"apiDockerImage\": \"${DOCKER_IMAGE_NAME}\"}}"
        > build_artifacts/${DEPLOY_TEMPLATE_PARAMETERS_FILE_NAME}

artifacts:
  base-directory: ./build_artifacts
  files:
    - ${DEPLOY_TEMPLATE_FILE_NAME}
    - ${DEPLOY_TEMPLATE_PARAMETERS_FILE_NAME}
