---
version: "2"

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8030:8000"
  server:
    build:
      context: .
    volumes:
      - ./dist:/opt/code/dist
      - ./src:/opt/code/src
      - ./server:/opt/code/server
      - ./shared:/opt/code/shared
    command: run dev:server
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=herp
      - AWS_SECRET_ACCESS_KEY=derp
      - AWS_REGION=eu-west-1
    ports:
      - "8000:8000"
